'use client';
import { memo, useEffect, useRef, useState, type ReactNode, type PointerEvent } from 'react';
import Image from 'next/image';
import * as m from 'motion/react-m';
import { LazyMotion, domAnimation, MotionConfig, useMotionValue, useSpring, useTransform, useScroll, useReducedMotion } from 'motion/react';
import { Asterisk, Plus, X, Menu, Copy, Check, Sun, Moon, ArrowUpRight, ArrowDown, Download, LockKeyhole, Code2 } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from '@/components/ui/dialog';
import { projects, type PortfolioProject } from './project-data';
import { MotionSequence, ScrollManifesto, KineticRibbon } from './portfolio-motion';

const MotionImage = m.create(Image);
const heroSizes = '(max-width: 479px) calc(100vw - 40px), (max-width: 767px) 440px, (max-width: 1100px) calc(53.4vw - 34px), (max-width: 1536px) calc(53.4vw - 51px), 770px';
const projectSizes = '(max-width: 767px) calc(100vw - 40px), (max-width: 1100px) calc(57vw - 59px), (max-width: 1536px) calc(57vw - 87px), 783px';

const email = 'anaytiwarii123@gmail.com';
const resume = '/documents/Anay-Tiwari-Resume-2026.pdf';
const spring = { stiffness: 160, damping: 20, mass: .5 };
const ease = [.22, 1, .36, 1] as const;
const history = [
  { date: 'Nov 2025 — Present', role: 'Software Engineer I · Full Stack', company: 'Datacultr', location: 'Gurugram, Haryana', text: 'Engineering multi-level RBAC dashboards, dynamic permission layers, and real-time data flows. Modernizing legacy sites with Next.js and headless WordPress, and improving Lighthouse performance from 40 to 85–90 through focused audits and optimization.' },
  { date: 'Jan 2024 — Oct 2025', role: 'Full Stack Developer', company: 'Clickvelo Digital', location: 'Jaipur, Rajasthan', text: 'Built a full-stack task management system with Next.js, Node.js, and MongoDB, helping improve team delivery speed by 40%. Launched four Next.js static sites and delivered 20+ custom WordPress websites across industries.' },
  { date: 'Jan 2023 — Dec 2023', role: 'Software Engineer I', company: 'Climbax Entertainment', location: 'Delhi, India', text: 'Shipped React and Next.js applications with reusable component libraries. Improved three core user flows, contributing to a 50% increase in retention over two quarters, and led debugging and code reviews that cut critical frontend issue resolution time by 60%.' },
];

function Reveal({ children, className = '', delay = 0 }: { children: ReactNode; className?: string; delay?: number }) {
  const reduce = useReducedMotion();
  return <m.div className={className} initial={reduce ? false : { opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .1 }} transition={{ duration: .8, ease, delay }}>{children}</m.div>;
}
function MagneticLink({ href, children, className = '', external = false, download = false }: { href: string; children: ReactNode; className?: string; external?: boolean; download?: boolean }) {
  const reduce = useReducedMotion(); const x = useMotionValue(0); const y = useMotionValue(0); const sx = useSpring(x, spring); const sy = useSpring(y, spring);
  function move(e: PointerEvent<HTMLAnchorElement>) { if (reduce || e.pointerType !== 'mouse') return; const b = e.currentTarget.getBoundingClientRect(); x.set((e.clientX - b.left - b.width / 2) * .14); y.set((e.clientY - b.top - b.height / 2) * .2); }
  return <m.a href={href} className={className} style={reduce ? {} : { x: sx, y: sy }} onPointerMove={move} onPointerLeave={() => { x.set(0); y.set(0); }} {...(external ? { target: '_blank', rel: 'noopener noreferrer' } : {})} {...(download ? { download: true } : {})}>{children}</m.a>;
}
function Header() {
  const reduce = useReducedMotion(); const [menu, setMenu] = useState(false); const [theme, setTheme] = useState('dark'); const [active, setActive] = useState('');
  useEffect(() => {
    try { const saved = localStorage.getItem('anay-theme'); if (saved === 'light' || saved === 'dark') { setTheme(saved); document.documentElement.dataset.theme = saved; } } catch {}
    const observer = new IntersectionObserver(entries => { entries.forEach(entry => { if (entry.isIntersecting) setActive(entry.target.id); }); }, { rootMargin: '-20% 0px -55% 0px' });
    ['projects', 'about', 'experience', 'contact'].forEach(id => { const el = document.getElementById(id); if (el) observer.observe(el); }); return () => observer.disconnect();
  }, []);
  const links = [['Work', 'projects'], ['About', 'about']];
  function toggleTheme() { const next = theme === 'dark' ? 'light' : 'dark'; setTheme(next); document.documentElement.dataset.theme = next; try { localStorage.setItem('anay-theme', next); } catch {} }
  return <><header className="site-header shell"><a href="/#home" className="wordmark" aria-label="Anay Tiwari home">anay<span>.</span><Asterisk aria-hidden="true" size={27} strokeWidth={1.5} /></a><nav className="desktop-nav" aria-label="Main navigation">{links.map(([label, id]) => <a key={id} className={active === id ? 'active' : ''} href={`/#${id}`}>{label}</a>)}</nav><div className="header-actions"><button className="theme-button" onClick={toggleTheme} aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} theme`}>{theme === 'dark' ? <Sun size={18} strokeWidth={1.5} /> : <Moon size={18} strokeWidth={1.5} />}</button><MagneticLink href="/#contact" className="pill-button header-contact">Let's talk<ArrowUpRight size={16} strokeWidth={1.5} /></MagneticLink><button className="menu-button" onClick={() => setMenu(true)} aria-label="Open navigation"><Menu size={24} strokeWidth={1.5} /></button></div></header>
    <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="navigation-dialog" showCloseButton={false}><DialogTitle className="sr-only">Navigation</DialogTitle><DialogDescription className="sr-only">Explore Anay's work and story.</DialogDescription><DialogClose className="dialog-x" aria-label="Close navigation"><X size={25} strokeWidth={1.5} /></DialogClose><span className="wordmark">anay<span>.</span></span><nav aria-label="Mobile navigation">{[...links, ['Experience', 'experience'], ["Let's talk", 'contact']].map(([label, id], i) => <m.a key={id} href={`/#${id}`} initial={reduce ? false : { opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: reduce ? 0 : i * .05, duration: reduce ? 0 : .5, ease }} onClick={() => setMenu(false)}>{label}</m.a>)}</nav><a className="text-link" href={`mailto:${email}`}>{email}</a></DialogContent></Dialog></>;
}
function Hero() {
  const ref = useRef<HTMLElement>(null); const reduce = useReducedMotion(); const { scrollYProgress } = useScroll({ target: ref, offset: ['start start', 'end start'] });
  const imageY = useTransform(scrollYProgress, [0, 1], [0, 130]); const imageRotate = useTransform(scrollYProgress, [0, 1], [0, 12]); const orbitRotate = useTransform(scrollYProgress, [0, 1], [-18, 45]);
  const px = useMotionValue(0); const py = useMotionValue(0); const rx = useSpring(px, spring); const ry = useSpring(py, spring);
  function pointer(e: PointerEvent<HTMLDivElement>) { if (reduce || e.pointerType !== 'mouse') return; const b = e.currentTarget.getBoundingClientRect(); px.set((e.clientX - b.left - b.width / 2) * .035); py.set((e.clientY - b.top - b.height / 2) * .035); }
  return <section id="home" ref={ref} className="hero shell"><div className="hero-copy"><m.p className="hero-label" initial={reduce ? false : { opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, ease }}>Full-stack developer / creative engineer</m.p><h1 aria-label="Anay Tiwari"><span className="type-mask"><m.span initial={reduce ? false : { y: '105%' }} animate={{ y: 0 }} transition={{ duration: 1, ease, delay: .1 }}>ANAY</m.span></span><span className="type-mask"><m.span initial={reduce ? false : { y: '105%' }} animate={{ y: 0 }} transition={{ duration: 1, ease, delay: .2 }}>TIWARI<span className="orange">.</span></m.span></span></h1><m.p className="hero-description" initial={reduce ? false : { opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, ease, delay: .4 }}>Interfaces that feel good. Systems that hold up.<br />I build the whole thing.</m.p><m.div initial={reduce ? false : { opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, ease, delay: .5 }}><MagneticLink href="/#projects" className="pill-button filled">See selected work<ArrowDown size={18} strokeWidth={1.5} /></MagneticLink></m.div></div>
    <m.div className="hero-visual" style={reduce ? {} : { y: imageY, rotate: imageRotate }} initial={reduce ? false : { opacity: 0, scale: .94 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 1.3, ease, delay: .15 }} onPointerMove={pointer} onPointerLeave={() => { px.set(0); py.set(0); }}><m.svg className="hero-orbit" viewBox="0 0 600 600" style={reduce ? {} : { rotate: orbitRotate }} aria-hidden="true"><ellipse cx="300" cy="300" rx="285" ry="190" fill="none" stroke="currentColor" strokeWidth=".6" strokeDasharray="2 8" /><circle cx="535" cy="191" r="9" fill="var(--accent)" /><path d="M36 263h28m-14-14v28M462 476h24m-12-12v24" fill="none" stroke="var(--accent)" strokeWidth="1.5" /></m.svg><m.div className="sculpture-inner" style={reduce ? {} : { x: rx, y: ry }}><Image src="/images/hero-sculpture.webp" width={1200} height={1200} sizes={heroSizes} quality={90} preload alt="Intertwined chrome and orange sculpture" /></m.div><div className="hero-art-caption"><span>Pixels. Plumbing. A little personality.</span><Code2 size={18} strokeWidth={1.5} /></div></m.div><div className="hero-foot"><span>Based in Gurugram, India</span><a href="/#projects">Keep going. It gets hands-on.<ArrowDown size={16} strokeWidth={1.5} /></a></div></section>;
}
const ProjectCard = memo(function ProjectCard({ project, index, onSelect }: { project: PortfolioProject; index: number; onSelect: (p: PortfolioProject) => void }) {
  const reduce = useReducedMotion(); const x = useMotionValue(0); const y = useMotionValue(0); const rotateX = useSpring(y, spring); const rotateY = useSpring(x, spring);
  const ref = useRef<HTMLDivElement>(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start end', 'end start'] }); const imageY = useTransform(scrollYProgress, [0, 1], ['-4%', '4%']);
  function tilt(e: PointerEvent<HTMLButtonElement>) { if (reduce || e.pointerType !== 'mouse') return; const b = e.currentTarget.getBoundingClientRect(); x.set((e.clientX - b.left - b.width / 2) / b.width * 4); y.set(-(e.clientY - b.top - b.height / 2) / b.height * 4); }
  return <Reveal className={`project project-${index}`}><button className="project-button" onClick={() => onSelect(project)} onPointerMove={tilt} onPointerLeave={() => { x.set(0); y.set(0); }} aria-label={`View ${project.name} project`}><m.div ref={ref} className={`project-image project-image-${index}`} style={reduce ? { backgroundColor: project.color } : { rotateX, rotateY, backgroundColor: project.color }}><MotionImage src={project.image} alt={`Concept cover artwork for ${project.name}`} width={1536} height={1024} sizes={projectSizes} quality={90} loading="lazy" style={reduce ? {} : { y: imageY }} /><span className="project-cover-label">{project.category === 'Product' ? 'Product engineering' : 'Web experience'}</span><span className="view-project"><ArrowUpRight size={23} strokeWidth={1.5} /><span>Explore</span></span></m.div><div className="project-caption"><div><h3>{project.name}</h3><p>{project.label}</p></div><span className="project-type">{project.category}</span></div></button></Reveal>;
});
function SelectedWork() {
  const [selected, setSelected] = useState<PortfolioProject | null>(null); const groups = [{ value: 'all', label: 'All work', projects }, { value: 'products', label: 'Products', projects: projects.filter(p => p.category === 'Product') }, { value: 'websites', label: 'Websites', projects: projects.filter(p => p.category === 'Website') }];
  return <section id="projects" className="work-section shell"><Reveal className="section-heading work-heading"><h2>A few things<br /><span className="outline">I've shipped.</span></h2><p>Real products, real workflows, and the edge cases that arrive uninvited.</p></Reveal><Tabs defaultValue="all" className="work-tabs"><TabsList aria-label="Filter selected work" className="work-filters">{groups.map(g => <TabsTrigger key={g.value} value={g.value}>{g.label}<span>{g.projects.length}</span></TabsTrigger>)}</TabsList>{groups.map(g => <TabsContent value={g.value} key={g.value}><div className="project-grid">{g.projects.map((p, i) => <ProjectCard key={p.id} project={p} index={i} onSelect={setSelected} />)}</div></TabsContent>)}</Tabs><Reveal className="private-code"><LockKeyhole size={23} strokeWidth={1.4} /><p>No GitHub links here. My clients like their code private,<br className="desktop-break" /> and I like having clients.</p><span>Source: trust me, it compiles.</span></Reveal>
    <Dialog open={selected !== null} onOpenChange={open => { if (!open) setSelected(null); }}><DialogContent className="project-dialog" showCloseButton={false}><DialogClose className="dialog-x" aria-label="Close project"><X size={22} strokeWidth={1.5} /></DialogClose>{selected && <><div className="project-dialog-cover"><Image src={selected.image} width={1536} height={1024} sizes="(max-width: 972px) calc(100vw - 32px), 940px" quality={90} loading="eager" alt={`Concept artwork for ${selected.name}`} /><span>Cover art inspired by the project</span></div><div className="project-dialog-copy"><p className="project-dialog-label">{selected.category === 'Product' ? 'Full-stack product engineering' : 'Website development'}</p><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.description}</DialogDescription><div className="tags">{selected.tags.map(t => <span key={t}>{t}</span>)}</div><ul className="project-details">{selected.details.map(d => <li key={d}>{d}</li>)}</ul></div><div className="project-dialog-bottom"><p>{selected.url ? 'The website is public. The client repository stays private.' : 'A private B2B product. Happy to talk through the engineering.'}</p>{selected.url ? <MagneticLink href={selected.url} external className="pill-button filled">View live site<ArrowUpRight size={18} /></MagneticLink> : <a href="/#contact" className="pill-button filled" onClick={() => setSelected(null)}>Discuss this build<ArrowUpRight size={18} /></a>}</div></>}</DialogContent></Dialog></section>;
}
function About() {
  return <section id="about" className="about-section shell"><Reveal className="about-heading"><h2>Curious by nature.<br /><span className="outline">Builder by default.</span></h2></Reveal><div className="about-grid"><Reveal className="portrait-wrap"><div className="portrait-frame"><img src="/images/avatar.webp" width="640" height="640" decoding="async" alt="Anay Tiwari" loading="lazy" /><span className="portrait-code" aria-hidden="true">&lt;human /&gt;</span><Asterisk className="portrait-star" size={88} strokeWidth={.8} aria-hidden="true" /></div><span className="portrait-caption">The human behind the &lt;div&gt;.</span></Reveal><Reveal className="about-copy" delay={.1}><p className="about-lead">Yes, I care about the pixels.<br />Also the plumbing.</p><p>I'm Anay, a full-stack developer based in Gurugram, India. I bring 3+ years of production experience across React, Next.js, Node.js, and MongoDB.</p><p>My work ranges from expressive brand websites to permission-driven dashboards and multi-tenant products. Lately, that includes visual search with Qdrant and CLIP, and applied GenAI with OpenRouter.</p><p>Still asking “why is this loading twice?”<br />Still enjoying the answer.</p><div className="about-links"><MagneticLink className="text-link" href={resume} download>Download résumé<Download size={17} strokeWidth={1.5} /></MagneticLink><a className="text-link" href="https://www.linkedin.com/in/anaytiwari/" target="_blank" rel="noopener noreferrer">LinkedIn<ArrowUpRight size={17} strokeWidth={1.5} /></a></div></Reveal></div><div className="stack-block"><h3>Tools I turn<br />into things.</h3><div className="stack-groups">{[['Interfaces', ['React.js', 'Next.js', 'JavaScript', 'Redux', 'SSR / SSG', 'HTML & CSS']], ['Systems', ['Node.js', 'Express.js', 'Django', 'MongoDB', 'MySQL', 'REST APIs', 'Socket.io']], ['Intelligence', ['Python', 'Qdrant', 'CLIP', 'OpenRouter', 'Vector search', 'MCP']], ['Delivery', ['AWS', 'Git', 'Lighthouse', 'Headless WordPress', 'Razorpay', 'Shiprocket']]].map(([title, list]) => <Reveal className="stack-group" key={title as string}><h4>{title}</h4><div>{(list as string[]).map(t => <span key={t}>{t}</span>)}</div></Reveal>)}</div></div></section>;
}
function Impact() {
  const reduce = useReducedMotion(); const ref = useRef<HTMLElement>(null); const { scrollYProgress } = useScroll({ target: ref, offset: ['start .85', 'center center'] }); const lineScale = useTransform(scrollYProgress, [0, 1], [.05, 1]);
  return <section ref={ref} className="impact-section shell" aria-labelledby="impact-heading"><Reveal className="section-heading impact-heading"><h2 id="impact-heading">Looks good.<br /><span className="outline">Works harder.</span></h2><p>A pretty interface earns the first click.<br />Good engineering earns the next one.</p></Reveal><div className="impact-layout"><Reveal className="speed-graphic"><div className="speed-values"><span className="speed-before">40<span>before</span></span><ArrowUpRight size={40} strokeWidth={1} aria-hidden="true" /><span className="speed-after">85–90<span>after</span></span></div><div className="speed-track"><m.div style={reduce ? {} : { scaleX: lineScale }} /><span /><span /><span /></div><p>Lighthouse performance score</p><span className="speed-caption">At Datacultr · legacy WordPress optimization</span></Reveal><Reveal className="impact-copy"><h3>The details add up.<br />The loading time shouldn't.</h3><p>Refactored render-blocking resources. Lazy-loaded assets. Compressed images. Modernized legacy architecture.</p><p>Small decisions. A much better experience.</p><div className="impact-result"><strong>40%</strong><span>Faster team delivery with a full-stack<br />task management system at Clickvelo.</span></div></Reveal></div></section>;
}
function Experience() {
  return <section id="experience" className="experience-section shell"><Reveal className="section-heading"><h2>More than<br /><span className="outline">a commit history.</span></h2><p>Good teams, useful problems, and a healthy amount of debugging.</p></Reveal><div className="experience-grid"><Reveal className="experience-aside"><Asterisk size={84} strokeWidth={.8} aria-hidden="true" /><p>3+ years of building.<br />Still plenty to learn.</p><MagneticLink className="text-link" href={resume} download>Download résumé<Download size={16} strokeWidth={1.5} /></MagneticLink></Reveal><Accordion type="single" collapsible defaultValue="0" className="experience-list">{history.map((h, i) => <Reveal key={h.company} delay={i * .06}><AccordionItem value={String(i)} className="experience-row"><AccordionTrigger className="experience-item"><span className="experience-date">{h.date}</span><span className="experience-role"><strong>{h.company}</strong><span>{h.role}</span></span><Plus size={20} strokeWidth={1.5} /></AccordionTrigger><AccordionContent className="experience-detail"><span className="experience-location">{h.location}</span>{h.text}</AccordionContent></AccordionItem></Reveal>)}</Accordion></div><Reveal className="education"><span>Education</span><div><h3>B.Tech · Computer science & engineering</h3><p>JK Lakshmipat University, Jaipur</p></div><span>Aug 2019 — May 2023</span></Reveal></section>;
}
function Contact() {
  const [copied, setCopied] = useState(false); const [copyError, setCopyError] = useState(false); const timer = useRef<ReturnType<typeof setTimeout> | null>(null); useEffect(() => () => { if (timer.current) clearTimeout(timer.current); }, []);
  async function copy() { try { await navigator.clipboard.writeText(email); setCopied(true); setCopyError(false); if (timer.current) clearTimeout(timer.current); timer.current = setTimeout(() => setCopied(false), 2500); } catch { setCopyError(true); } }
  return <footer id="contact" className="contact-section"><div className="shell"><Reveal className="contact-heading"><p className="eyebrow">A messy idea is a perfectly good start.</p><h2>Let's make<br /><span>something matter.</span><Asterisk size={90} strokeWidth={1} aria-hidden="true" /></h2></Reveal><div className="contact-lower"><div><MagneticLink href={`mailto:${email}`} className="contact-email">{email}</MagneticLink><button className="copy-email" onClick={copy}>{copied ? <Check size={16} strokeWidth={1.5} /> : <Copy size={16} strokeWidth={1.5} />}<span aria-live="polite">{copied ? 'Copied. Your move.' : 'Copy email'}</span></button>{copyError && <p className="copy-error" role="status">Select the email address above to copy it.</p>}</div><MagneticLink href={`mailto:${email}`} className="pill-button contact-cta">Email Anay<ArrowUpRight size={20} strokeWidth={1.5} /></MagneticLink></div><div className="footer-bottom"><a href="/#home" className="footer-logo">anay.</a><p>Gurugram, Haryana, India</p><div><a href="https://www.linkedin.com/in/anaytiwari/" target="_blank" rel="noopener noreferrer">LinkedIn</a><a href={resume} download>Résumé</a></div><span>© {new Date().getFullYear()} Anay Tiwari</span></div><p className="footer-note">Built with intent. And a suspicious number of browser tabs.</p></div></footer>;
}
export default function Portfolio() {
  const reduce = useReducedMotion(); const { scrollYProgress } = useScroll(); const progress = useSpring(scrollYProgress, { stiffness: 100, damping: 30 });
  return <LazyMotion features={domAnimation} strict><MotionConfig reducedMotion="user"><a href="#main" className="skip-link">Skip to content</a><m.div className="page-progress" style={{ scaleX: reduce ? scrollYProgress : progress }} aria-hidden="true" /><Header /><main id="main"><Hero /><section className="manifesto-section shell" aria-label="Creative approach"><ScrollManifesto /><div className="manifesto-aside"><Asterisk size={52} strokeWidth={1} aria-hidden="true" /><p>Good ideas deserve<br />a little extra attention.</p><span>Scroll for the evidence ↓</span></div></section><SelectedWork /><KineticRibbon /><MotionSequence /><About /><Impact /><Experience /></main><Contact /></MotionConfig></LazyMotion>;
}
